### ISSUE TITLE
Problem with weird Spline Behavior

### ISSUE THREAD

**Issue by Choccy-vr** [CMDRSpirit/RollercoasterDesigner#6]
Hello I am having a problem that whenever I make a new track section and it is a drop the start slope gets put to a weird value no matter the value you set it to. (This only happens once you go into play mode) The Start slope value no matter what you actually set it to. It always sets Y to -0.2812195 and Z to 24.93537. and there is only one error ```
NullReferenceException: Object reference not set to an instance of an object
Rollercoaster.CoasterTrack.DeltaMToDeltaTNegative (System.Single t0, System.Single deltaM) (at Assets/RollercoasterDesigner-main/Scripts/CoasterTrack.cs:150)
Rollercoaster.CoasterTrain.PlaceTrainOnTrack () (at Assets/RollercoasterDesigner-main/Scripts/CoasterTrain.cs:130)
Rollercoaster.CoasterTrain.OnValidate () (at Assets/RollercoasterDesigner-main/Scripts/CoasterTrain.cs:64)

```
When I was debugging I narrowed it down to this line `float3 startSlope = lengthsq(StartSlope) != 0 ? StartSlope : float.NaN;` in TrackSection.cs but I might be wrong. Also when you try to make a vertical loop or any other loop it glitches out at makes it so you are not inverted.

**Comment by CMDRSpirit** [comment]
That is intended behavior, because it sets it to the same value the previous track section ended with. Otherwise you don't get a smooth transition between the track sections.

Regarding the vertical loop, try using more nodes for the loop (5+), maybe that helps as the resampling can produce weird results otherwise.

Your error is likely related to a track section object being null, which can happen when the `TrackSections` variable contains invalid elements. This may be the result of removing a track section and something not working correctly in the background...

**Comment by Choccy-vr** [comment]
Got it thanks
